window.PRODUCTS = [
  {
    id: "tee",
    name: "Skeleton Graphic Tee",
    category: "T-shirt",
    price: 29,
    image: "assets/product-tee.png",
    page: "product-tee.html",
    alt: "Black skeleton graphic T-shirt",
    description: "Black oversized tee with a front skeleton graphic.",
    options: ["S", "M", "L", "XL"],
    specs: [["Fit", "Oversized"], ["Color", "Black"], ["Material", "Cotton jersey"]],
  },
  {
    id: "tee-offwhite-small",
    name: "Small Skull Tee / Off White",
    category: "T-shirt",
    price: 29,
    image: "assets/product-tee-offwhite-small.png",
    page: "product-tee.html",
    alt: "Off-white T-shirt with small skull mark",
    description: "Off-white oversized tee with a small Boney skull mark.",
    options: ["S", "M", "L", "XL"],
    specs: [["Fit", "Oversized"], ["Color", "Off white"], ["Detail", "Small chest mark"]],
  },
  {
    id: "tee-gray-back",
    name: "Escape Back Print Tee / Gray",
    category: "T-shirt",
    price: 32,
    image: "assets/product-tee-gray-back.png",
    page: "product-tee.html",
    alt: "Heather gray T-shirt with skeleton print",
    description: "Heather gray tee with a larger skeleton escape graphic.",
    options: ["S", "M", "L", "XL"],
    specs: [["Fit", "Oversized"], ["Color", "Heather gray"], ["Detail", "Large graphic print"]],
  },
  {
    id: "tee-charcoal-small",
    name: "Minimal Skull Tee / Charcoal",
    category: "T-shirt",
    price: 29,
    image: "assets/product-tee-charcoal-small.png",
    page: "product-tee.html",
    alt: "Dark charcoal T-shirt with small skull mark",
    description: "Dark charcoal tee with a minimal skull detail.",
    options: ["S", "M", "L", "XL"],
    specs: [["Fit", "Oversized"], ["Color", "Charcoal"], ["Detail", "Minimal skull mark"]],
  },
  {
    id: "cap",
    name: "Skull Embroidery Cap",
    category: "Cap",
    price: 24,
    image: "assets/product-cap.png",
    page: "product-cap.html",
    alt: "Cream cap with skull embroidery",
    description: "Cream cap with a small skull embroidery mark.",
    options: ["One size"],
    specs: [["Fit", "Adjustable"], ["Color", "Cream"], ["Detail", "Front embroidery"]],
  },
  {
    id: "mug",
    name: "Skeleton Face Mug",
    category: "Mug",
    price: 18,
    image: "assets/product-mug.png",
    page: "product-mug.html",
    alt: "Ceramic mug with skeleton face graphic",
    description: "Ceramic mug with a bold skeleton face graphic.",
    options: ["11 oz"],
    specs: [["Material", "Ceramic"], ["Finish", "Matte"], ["Care", "Hand wash recommended"]],
  },
  {
    id: "mug-makeover",
    name: "Wanted Makeover Mug",
    category: "Episode mug",
    price: 20,
    image: "assets/product-mug-makeover.png",
    page: "product-mug-makeover.html",
    alt: "White mug with Boney skeleton peace sign graphic",
    description: "White ceramic mug inspired by the Wanted: A Makeover short, featuring Boney inside a gray round badge.",
    options: ["11 oz"],
    specs: [["Material", "Ceramic"], ["Design", "Boney peace sign badge"], ["Episode", "Wanted: A Makeover"]],
  },
  {
    id: "blind-box",
    name: "Mystery Skeleton Box",
    category: "Blind box",
    price: 16,
    image: "assets/product-blind-box.png",
    page: "product-blind-box.html",
    alt: "Skeleton IP blind box package",
    description: "Mystery box concept for the skeleton collectible line.",
    options: ["Random"],
    specs: [["Type", "Blind box"], ["Series", "First drop"], ["Note", "One random design"]],
  },
  {
    id: "figure",
    name: "Desk Skeleton Figure",
    category: "Figure",
    price: 39,
    image: "assets/product-figure.png",
    page: "product-figure.html",
    alt: "Skeleton desk figure collectible",
    description: "Small desk figure collectible based on the skeleton character.",
    options: ["Standard"],
    specs: [["Type", "Desk figure"], ["Finish", "Vinyl style"], ["Height", "Approx. 10 cm"]],
  },
  {
    id: "stickers",
    name: "Skeleton Sticker Sheet",
    category: "Stickers",
    price: 9,
    image: "assets/product-stickers.png",
    page: "product-stickers.html",
    alt: "Skeleton sticker sheet",
    description: "Sticker sheet with skull, bone, and mini character graphics.",
    options: ["Sheet"],
    specs: [["Type", "Die-cut sheet"], ["Finish", "Matte"], ["Size", "A5 concept"]],
  },
];
